-- test: experimental source labels must not imply confidence stars.
local helpers=require("tests.helpers")
describe("experimental icon badge",function()
    it("reuses the badge field and clears it when reference mode resumes",function()
        local RA,ns=helpers.loadAddon()
        assert(helpers.loadAddonFile("addon/UI/Theme.lua","RotaAssist",ns))
        assert(helpers.loadAddonFile("addon/UI/Widgets/IconWidget.lua","RotaAssist",ns))
        local icon=RA.UI.IconWidget:Create(CreateFrame("Frame"),48)
        icon:SetConfidence(0.9)
        icon:SetSourceLabel("EXP")
        assert.equals("EXP",icon.confidence:GetText())
        icon:SetConfidence(0)
        assert.equals("",icon.confidence:GetText())
    end)
end)
