-- test: add-only regressions for immediate recommendations and static cues.
local helpers = require("tests.helpers")
describe("accessible recommendation icons", function()
    local RA, icon
    before_each(function()
        local ns; RA, ns = helpers.loadAddon()
        RA.L = { RANGE_BADGE = "Range" }
        helpers.loadAddonFile("addon/UI/Theme.lua", "RotaAssist", ns)
        helpers.loadAddonFile("addon/UI/Widgets/GlowWidget.lua", "RotaAssist", ns)
        helpers.loadAddonFile("addon/UI/Widgets/IconWidget.lua", "RotaAssist", ns)
        icon = RA.UI.IconWidget:Create(CreateFrame("Frame"), 48)
    end)
    it("updates immediately without a delayed texture callback in reduced motion", function()
        icon:SetReducedMotion(true); icon:SetSpell(100, 200)
        assert.equals(200, icon.icon:GetTexture()); assert.is_nil(icon.fadeTimer)
        assert.equals(1, icon.frame:GetAlpha())
    end)
    it("finishes a pending texture swap when reduced motion is enabled", function()
        icon:SetSpell(100, 200); assert.is_not_nil(icon.fadeTimer)
        icon:SetReducedMotion(true)
        assert.is_nil(icon.fadeTimer); assert.equals(200, icon.icon:GetTexture())
    end)
    it("uses static range and glow cues and retains a text label", function()
        icon:SetReducedMotion(true); icon:SetGlow(true); icon:SetOutOfRange(true); icon:SetAlert(true)
        assert.is_false(icon.oorAnim:IsPlaying()); assert.is_false(icon.alertAnim:IsPlaying())
        assert.is_true(icon.focusFrame:IsShown()); assert.is_true(icon.alertFrame:IsShown())
        assert.equals("Range", icon.rangeText:GetText())
        icon:SetOutOfRange(false); assert.equals("", icon.rangeText:GetText())
    end)
    it("can restore motion and clear all transient cues", function()
        icon:SetReducedMotion(true); icon:SetOutOfRange(true); icon:SetAlert(true)
        icon:SetReducedMotion(false)
        assert.is_true(icon.oorAnim:IsPlaying()); assert.is_true(icon.alertAnim:IsPlaying())
        icon:Clear(); assert.is_false(icon.oorAnim:IsPlaying()); assert.is_false(icon.focusFrame:IsShown())
        assert.equals("", icon.rangeText:GetText()); assert.is_nil(icon.currentTexture)
    end)
    it("property: rapid changes show the latest texture with no pending timer", function()
        icon:SetReducedMotion(true)
        for i = 1, 120 do
            icon:SetSpell(1000 + i, 2000 + i)
            assert.equals(2000 + i, icon.icon:GetTexture()); assert.is_nil(icon.fadeTimer)
            if i % 7 == 0 then icon:Clear() end
        end
    end)
    it("never displays a misleading partial key combination", function()
        icon.keybind.GetStringWidth = function() return 500 end
        icon:SetKeybind("CTRL-ALT-SHIFT-F12")
        assert.equals("", icon.keybind:GetText())
        icon.keybind.GetStringWidth = function() return 20 end
        icon:SetKeybind("S-F"); assert.equals("S-F", icon.keybind:GetText())
    end)
end)
