--- RotaAssist Decision Tree (specID 63)
--- Auto-generated by sklearn2lua.py on 2026-04-28
--- DO NOT EDIT MANUALLY - regenerate with training/train_decision_tree.py
--- Tree depth: 10, Nodes: 279, Training accuracy: 73.7%
-- 自動生成の決定木ファイル / 自动生成的决策树文件，请勿手动编辑

local _, NS = ...
local RA = NS.RA
local DT = {}

DT.specID = 63
DT.generatedDate = "2026-04-28"
DT.treeDepth = 10
DT.trainingAccuracy = 0.7373

--- Evaluate the decision tree with given features.
--- @param features table
--- @return table|nil {spellID=number, confidence=number}
function DT.Evaluate(features)
    if features.blizzardRecommendation <= 7157 then
        if features.blizzardRecommendation <= 2534 then
            if features.blizzardRecommendation <= 1126 then
                if features.timeSinceLastCast <= 0.7150 then
                    if features.combatDuration <= 168.1500 then
                        return {spellID=133, confidence=0.5500}
                    else
                        return {spellID=133, confidence=0.6000}
                    end
                else
                    if features.secondLastSpellID <= 131207 then
                        if features.secondaryResource <= 1.5000 then
                            if features.combatDuration <= 102.0500 then
                                return {spellID=133, confidence=0.8065}
                            else
                                if features.thirdLastSpellID <= 76655 then
                                    return {spellID=133, confidence=0.7308}
                                else
                                    return {spellID=133, confidence=0.5000}
                                end
                            end
                        else
                            if features.combatDuration <= 245.7000 then
                                if features.thirdLastSpellID <= 171940 then
                                    if features.timeSinceLastCast <= 1.8500 then
                                        if features.nameplateCount <= 1.5000 then
                                            return {spellID=133, confidence=0.6000}
                                        else
                                            return {spellID=133, confidence=0.5500}
                                        end
                                    else
                                        return {spellID=133, confidence=0.7632}
                                    end
                                else
                                    return {spellID=133, confidence=0.8421}
                                end
                            else
                                return {spellID=133, confidence=0.9286}
                            end
                        end
                    else
                        if features.timeSinceLastCast <= 1.0450 then
                            return {spellID=133, confidence=0.8500}
                        else
                            if features.timeSinceLastCast <= 1.4150 then
                                return {spellID=133, confidence=0.4000}
                            else
                                if features.combatDuration <= 161.8000 then
                                    if features.secondaryResource <= 2.5000 then
                                        return {spellID=133, confidence=0.6286}
                                    else
                                        return {spellID=133, confidence=0.4583}
                                    end
                                else
                                    if features.nameplateCount <= 2.5000 then
                                        return {spellID=133, confidence=0.8929}
                                    else
                                        return {spellID=133, confidence=0.6087}
                                    end
                                end
                            end
                        end
                    end
                end
            else
                if features.nameplateCount <= 3.5000 then
                    if features.timeSinceLastCast <= 1.9950 then
                        if features.combatDuration <= 127.6000 then
                            return {spellID=133, confidence=0.4783}
                        else
                            return nil  -- low confidence 0.27
                        end
                    else
                        return nil  -- low confidence 0.22
                    end
                else
                    if features.secondaryResource <= 0.5000 then
                        return {spellID=2120, confidence=1.0000}
                    else
                        if features.lastSpellID <= 7157 then
                            if features.secondaryResource <= 3.5000 then
                                if features.lastSpellID <= 2534 then
                                    return {spellID=2120, confidence=0.8462}
                                else
                                    return {spellID=2120, confidence=0.7500}
                                end
                            else
                                return {spellID=2120, confidence=0.9459}
                            end
                        else
                            if features.combatDuration <= 233.0000 then
                                if features.timeSinceLastCast <= 2.2600 then
                                    if features.combatDuration <= 145.4500 then
                                        return {spellID=2120, confidence=1.0000}
                                    else
                                        return {spellID=2120, confidence=0.9189}
                                    end
                                else
                                    if features.combatDuration <= 97.1000 then
                                        return {spellID=2120, confidence=0.8182}
                                    else
                                        return {spellID=2120, confidence=1.0000}
                                    end
                                end
                            else
                                if features.lastSpellID <= 171940 then
                                    return {spellID=2120, confidence=0.7917}
                                else
                                    return {spellID=2120, confidence=0.9500}
                                end
                            end
                        end
                    end
                end
            end
        else
            if features.nameplateCount <= 4.5000 then
                if features.lastSpellID <= 171940 then
                    if features.timeSinceLastCast <= 0.6350 then
                        return {spellID=2948, confidence=0.8077}
                    else
                        if features.timeSinceLastCast <= 1.8250 then
                            if features.combatDuration <= 32.6000 then
                                return {spellID=2948, confidence=0.7000}
                            else
                                if features.timeSinceLastCast <= 1.6550 then
                                    if features.combatDuration <= 262.2500 then
                                        if features.combatDuration <= 73.0000 then
                                            return {spellID=2948, confidence=0.8000}
                                        else
                                            return {spellID=2948, confidence=0.9320}
                                        end
                                    else
                                        return {spellID=2948, confidence=0.7826}
                                    end
                                else
                                    return {spellID=2948, confidence=0.7500}
                                end
                            end
                        else
                            if features.combatDuration <= 242.5500 then
                                if features.timeSinceLastCast <= 2.6700 then
                                    if features.timeSinceLastCast <= 2.1850 then
                                        return {spellID=2948, confidence=0.9412}
                                    else
                                        if features.secondLastSpellID <= 27912 then
                                            return {spellID=2948, confidence=0.9500}
                                        else
                                            return {spellID=2948, confidence=1.0000}
                                        end
                                    end
                                else
                                    return {spellID=2948, confidence=0.9000}
                                end
                            else
                                if features.combatDuration <= 259.8000 then
                                    return {spellID=2948, confidence=0.7727}
                                else
                                    return {spellID=2948, confidence=0.9600}
                                end
                            end
                        end
                    end
                else
                    if features.combatDuration <= 59.0000 then
                        return {spellID=2948, confidence=0.6296}
                    else
                        if features.secondaryResource <= 4.5000 then
                            if features.secondaryResource <= 2.5000 then
                                if features.timeSinceLastCast <= 0.9850 then
                                    return {spellID=2948, confidence=0.9500}
                                else
                                    if features.thirdLastSpellID <= 131207 then
                                        return {spellID=2948, confidence=0.7273}
                                    else
                                        return {spellID=2948, confidence=0.9091}
                                    end
                                end
                            else
                                if features.timeSinceLastCast <= 1.5450 then
                                    return {spellID=2948, confidence=0.9000}
                                else
                                    return {spellID=2948, confidence=1.0000}
                                end
                            end
                        else
                            return {spellID=2948, confidence=0.7241}
                        end
                    end
                end
            else
                if features.timeSinceLastCast <= 2.4350 then
                    if features.lastSpellID <= 2534 then
                        return {spellID=2948, confidence=0.7143}
                    else
                        if features.combatDuration <= 76.9500 then
                            return {spellID=2948, confidence=0.6667}
                        else
                            if features.combatDuration <= 208.9000 then
                                return {spellID=2948, confidence=1.0000}
                            else
                                return {spellID=2948, confidence=0.7931}
                            end
                        end
                    end
                else
                    return {spellID=2948, confidence=0.6400}
                end
            end
        end
    else
        if features.blizzardRecommendation <= 27912 then
            if features.nameplateCount <= 6.5000 then
                if features.thirdLastSpellID <= 171940 then
                    if features.timeSinceLastCast <= 1.0500 then
                        if features.secondaryResource <= 1.5000 then
                            return {spellID=11366, confidence=0.6579}
                        else
                            if features.combatDuration <= 108.8000 then
                                return {spellID=11366, confidence=0.8000}
                            else
                                return {spellID=11366, confidence=1.0000}
                            end
                        end
                    else
                        if features.secondaryResource <= 3.5000 then
                            if features.lastSpellID <= 7157 then
                                if features.combatDuration <= 152.7500 then
                                    if features.timeSinceLastCast <= 2.2350 then
                                        return {spellID=11366, confidence=1.0000}
                                    else
                                        return {spellID=11366, confidence=0.9000}
                                    end
                                else
                                    return {spellID=11366, confidence=0.7812}
                                end
                            else
                                if features.secondLastSpellID <= 223930 then
                                    if features.nameplateCount <= 2.5000 then
                                        if features.timeSinceLastCast <= 1.6700 then
                                            return {spellID=11366, confidence=0.9524}
                                        else
                                            return {spellID=11366, confidence=1.0000}
                                        end
                                    else
                                        if features.timeSinceLastCast <= 2.2250 then
                                            return {spellID=11366, confidence=0.8519}
                                        else
                                            return {spellID=11366, confidence=1.0000}
                                        end
                                    end
                                else
                                    return {spellID=11366, confidence=0.8710}
                                end
                            end
                        else
                            if features.combatDuration <= 98.5000 then
                                return {spellID=11366, confidence=0.7879}
                            else
                                if features.secondLastSpellID <= 27912 then
                                    return {spellID=11366, confidence=0.8095}
                                else
                                    if features.timeSinceLastCast <= 1.9850 then
                                        return {spellID=11366, confidence=1.0000}
                                    else
                                        return {spellID=11366, confidence=0.8571}
                                    end
                                end
                            end
                        end
                    end
                else
                    if features.timeSinceLastCast <= 2.5300 then
                        if features.timeSinceLastCast <= 2.1200 then
                            if features.timeSinceLastCast <= 1.5350 then
                                if features.combatDuration <= 59.6500 then
                                    return {spellID=11366, confidence=0.9091}
                                else
                                    if features.combatDuration <= 147.7500 then
                                        return {spellID=11366, confidence=0.5238}
                                    else
                                        if features.secondLastSpellID <= 76655 then
                                            return {spellID=11366, confidence=0.9048}
                                        else
                                            return {spellID=11366, confidence=0.7391}
                                        end
                                    end
                                end
                            else
                                return {spellID=11366, confidence=0.9459}
                            end
                        else
                            return {spellID=11366, confidence=0.5862}
                        end
                    else
                        return {spellID=11366, confidence=0.9333}
                    end
                end
            else
                if features.thirdLastSpellID <= 76655 then
                    return {spellID=11366, confidence=0.6216}
                else
                    if features.combatDuration <= 121.8000 then
                        return {spellID=11366, confidence=1.0000}
                    else
                        return {spellID=11366, confidence=0.7619}
                    end
                end
            end
        else
            if features.blizzardRecommendation <= 319990 then
                if features.blizzardRecommendation <= 223930 then
                    if features.blizzardRecommendation <= 171940 then
                        if features.blizzardRecommendation <= 131207 then
                            if features.blizzardRecommendation <= 76655 then
                                if features.nameplateCount <= 3.5000 then
                                    if features.combatDuration <= 228.4500 then
                                        if features.timeSinceLastCast <= 2.3600 then
                                            return {spellID=11366, confidence=0.3333}
                                        else
                                            return nil  -- low confidence 0.21
                                        end
                                    else
                                        return {spellID=2948, confidence=0.3571}
                                    end
                                else
                                    if features.timeSinceLastCast <= 1.5900 then
                                        return {spellID=2120, confidence=0.4500}
                                    else
                                        return {spellID=153561, confidence=0.3333}
                                    end
                                end
                            else
                                if features.nameplateCount <= 4.5000 then
                                    if features.combatDuration <= 30.6000 then
                                        return {spellID=108853, confidence=0.5500}
                                    else
                                        if features.timeSinceLastCast <= 1.3850 then
                                            return {spellID=108853, confidence=0.8625}
                                        else
                                            return {spellID=108853, confidence=0.7461}
                                        end
                                    end
                                else
                                    if features.secondaryResource <= 2.5000 then
                                        return {spellID=108853, confidence=0.5000}
                                    else
                                        if features.secondLastSpellID <= 27912 then
                                            return {spellID=108853, confidence=0.7000}
                                        else
                                            return {spellID=108853, confidence=0.7273}
                                        end
                                    end
                                end
                            end
                        else
                            if features.nameplateCount <= 4.5000 then
                                if features.timeSinceLastCast <= 2.8450 then
                                    if features.timeSinceLastCast <= 0.6500 then
                                        return {spellID=153561, confidence=0.5909}
                                    else
                                        if features.secondLastSpellID <= 1126 then
                                            return {spellID=153561, confidence=0.9630}
                                        else
                                            return {spellID=153561, confidence=0.7549}
                                        end
                                    end
                                else
                                    return {spellID=153561, confidence=0.5000}
                                end
                            else
                                if features.secondaryResource <= 3.5000 then
                                    if features.lastSpellID <= 76655 then
                                        return {spellID=153561, confidence=0.3500}
                                    else
                                        return {spellID=153561, confidence=0.5455}
                                    end
                                else
                                    return {spellID=153561, confidence=0.7742}
                                end
                            end
                        end
                    else
                        if features.combatDuration <= 163.6000 then
                            if features.nameplateCount <= 6.5000 then
                                if features.secondaryResource <= 1.5000 then
                                    if features.combatDuration <= 114.5000 then
                                        if features.timeSinceLastCast <= 1.5400 then
                                            return {spellID=190319, confidence=0.7391}
                                        else
                                            return {spellID=190319, confidence=0.5357}
                                        end
                                    else
                                        return {spellID=190319, confidence=0.8636}
                                    end
                                else
                                    if features.secondLastSpellID <= 171940 then
                                        if features.timeSinceLastCast <= 2.3550 then
                                            return {spellID=190319, confidence=0.8630}
                                        else
                                            return {spellID=190319, confidence=1.0000}
                                        end
                                    else
                                        return {spellID=190319, confidence=0.7500}
                                    end
                                end
                            else
                                return {spellID=190319, confidence=0.6250}
                            end
                        else
                            if features.combatDuration <= 182.9000 then
                                return {spellID=190319, confidence=0.3929}
                            else
                                if features.combatDuration <= 207.1000 then
                                    return {spellID=190319, confidence=0.8649}
                                else
                                    if features.timeSinceLastCast <= 1.6450 then
                                        if features.combatDuration <= 255.6000 then
                                            return {spellID=190319, confidence=0.5200}
                                        else
                                            return {spellID=190319, confidence=0.7742}
                                        end
                                    else
                                        if features.combatDuration <= 257.8500 then
                                            return {spellID=190319, confidence=0.5806}
                                        else
                                            return {spellID=190319, confidence=0.4167}
                                        end
                                    end
                                end
                            end
                        end
                    end
                else
                    if features.nameplateCount <= 4.5000 then
                        if features.secondaryResource <= 2.5000 then
                            if features.timeSinceLastCast <= 2.5850 then
                                if features.combatDuration <= 78.8500 then
                                    return {spellID=257541, confidence=0.6667}
                                else
                                    if features.nameplateCount <= 2.5000 then
                                        if features.combatDuration <= 228.2500 then
                                            return {spellID=257541, confidence=0.8696}
                                        else
                                            return {spellID=257541, confidence=0.7083}
                                        end
                                    else
                                        return {spellID=257541, confidence=1.0000}
                                    end
                                end
                            else
                                return {spellID=257541, confidence=0.5833}
                            end
                        else
                            if features.timeSinceLastCast <= 2.2750 then
                                if features.combatDuration <= 224.5500 then
                                    if features.thirdLastSpellID <= 7157 then
                                        return {spellID=257541, confidence=0.4500}
                                    else
                                        if features.timeSinceLastCast <= 1.4100 then
                                            return {spellID=257541, confidence=0.7778}
                                        else
                                            return {spellID=257541, confidence=0.5417}
                                        end
                                    end
                                else
                                    return {spellID=257541, confidence=0.4857}
                                end
                            else
                                if features.combatDuration <= 177.5000 then
                                    return {spellID=257541, confidence=0.9583}
                                else
                                    return {spellID=257541, confidence=0.7500}
                                end
                            end
                        end
                    else
                        if features.combatDuration <= 129.2500 then
                            return {spellID=257541, confidence=0.5357}
                        else
                            if features.nameplateCount <= 7.5000 then
                                return {spellID=257541, confidence=0.8205}
                            else
                                return {spellID=257541, confidence=0.6190}
                            end
                        end
                    end
                end
            else
                if features.nameplateCount <= 3.5000 then
                    if features.combatDuration <= 130.7500 then
                        if features.combatDuration <= 44.6000 then
                            return {spellID=382440, confidence=0.8421}
                        else
                            if features.combatDuration <= 100.5500 then
                                if features.combatDuration <= 73.3000 then
                                    return {spellID=382440, confidence=0.5000}
                                else
                                    return {spellID=382440, confidence=0.7419}
                                end
                            else
                                return {spellID=382440, confidence=0.4667}
                            end
                        end
                    else
                        if features.timeSinceLastCast <= 2.1650 then
                            if features.timeSinceLastCast <= 1.3650 then
                                if features.lastSpellID <= 7157 then
                                    return {spellID=382440, confidence=0.9000}
                                else
                                    if features.thirdLastSpellID <= 131207 then
                                        return {spellID=382440, confidence=0.7619}
                                    else
                                        return {spellID=382440, confidence=0.8000}
                                    end
                                end
                            else
                                if features.combatDuration <= 184.4000 then
                                    return {spellID=382440, confidence=0.8182}
                                else
                                    if features.combatDuration <= 240.0000 then
                                        return {spellID=382440, confidence=0.4783}
                                    else
                                        return {spellID=382440, confidence=0.7000}
                                    end
                                end
                            end
                        else
                            if features.combatDuration <= 214.4500 then
                                return {spellID=382440, confidence=0.8148}
                            else
                                return {spellID=382440, confidence=1.0000}
                            end
                        end
                    end
                else
                    if features.combatDuration <= 36.5000 then
                        return {spellID=382440, confidence=0.4500}
                    else
                        if features.secondLastSpellID <= 7157 then
                            return {spellID=382440, confidence=0.5667}
                        else
                            if features.combatDuration <= 152.9500 then
                                return {spellID=382440, confidence=0.8333}
                            else
                                if features.combatDuration <= 232.0500 then
                                    return {spellID=382440, confidence=0.4545}
                                else
                                    return {spellID=382440, confidence=0.7500}
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

RA.DecisionTrees = RA.DecisionTrees or {}
RA.DecisionTrees[63] = DT
